### ISSUE TITLE
macOS: SystemExit error message box when quitting from dock

### ISSUE THREAD

**Issue by TV4Fun** [Pidgeot/python-lnp#182]
Using PyLNP 0.14b with macOS Monterey 12.6 (21G115). Right clicking on the dock and clicking quit, or going to quit from the Dwarf Fortress LNP menu, or typing cmd+Q produces this error message in a popup box before closing.

```{Traceback (most recent call last):
} {  File "python_lnp/launch.py", line 12, in <module>
} {  File "python_lnp/core/lnp.py", line 126, in __init__
} {  File "python_lnp/tkgui/tkgui.py", line 266, in start
} {  File "tkinter/__init__.py", line 1283, in mainloop
} {  File "tkinter/__init__.py", line 288, in _exit
} {SystemExit: 0
}
```

**Comment by TV4Fun** [comment]
This only seems to happen with the release build. I checked out the repo and used PyInstaller to build an app package, and that version doesn't do this. I don't know if this is a recent change of your, or if it's because I'm running on an M1 machine, the released version is an Intel binary, and the version PyInstaller made on my machine was an ARM binary.

**Comment by Pidgeot** [comment]
The build machine is completely unchanged, and there shouldn't have been any change to this part of the code when compared with 0.14a.

Unfortunately I don't really have any other machines to test it on, so it's quite difficult for me to guess as to why it's interpreting the exit request as an exception...

**Comment by TV4Fun** [comment]
I'm guessing it has to do with [this line](https://github.com/Pidgeot/python-lnp/blob/master/launch.py#L13) here. You have a `try` with an overly broad `except` clause that is catching the `SystemExit` exception and opening an error dialogue. That can probably be fixed by catching `SystemExit` separately and re-raising it, but I don't know why it's not happening on my checked out copy, and I'm not entirely comfortable submitting a fix for something I can't reproduce.

**Comment by TV4Fun** [comment]
@Pidgeot, what version of Python are you using when you build this? There was [a bug in tkinter](https://github.com/python/cpython/issues/60787) fixed about 10 years ago that may be responsible for this.

**Comment by Pidgeot** [comment]
It's using Python 3.7, and I just checked that this change is indeed applied here.

But yeah, explicitly looking for SystemExit is probably the right choice, although why it's only the Mac version doing this is beyond me... let me prepare a fix and do a new set of builds.

**Comment by Pidgeot** [comment]
New build is up as 0.14c. Hopefully this'll take care of it.

**Comment by TV4Fun** [comment]
Yeah, it's fixed now. Thank you for the quick turnaround.
